// Code is generated by Telerik Add OpenAccess Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using oaWebNotes;

namespace WebNotes_Rest
{
	public partial class NoteRepository : OpenAccessBaseRepository<oaWebNotes.Note, oaWebNotes.emWebNotes>
    {
	
    }

}
