#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace oaWebNotes	
{
	[Table("Categories")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Category
	{
		private int _fID;
		[Column("FID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_fID")]
		public virtual int FID 
		{ 
		    get
		    {
		        return this._fID;
		    }
		    set
		    {
		        this._fID = value;
		    }
		}
		
		private string _fNAME;
		[Column("FNAME", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 40, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fNAME")]
		public virtual string FNAME 
		{ 
		    get
		    {
		        return this._fNAME;
		    }
		    set
		    {
		        this._fNAME = value;
		    }
		}
		
	}
}
