#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;


namespace oaWebNotes	
{
	[Table("Notes")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Note
	{
		private int _fID;
		[Column("FID", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_fID")]
		public virtual int FID 
		{ 
		    get
		    {
		        return this._fID;
		    }
		    set
		    {
		        this._fID = value;
		    }
		}
		
		private string _fTITLE;
		[Column("FTITLE", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsNullable = true, Length = 50, Scale = 0, SqlType = "nvarchar")]
		[Storage("_fTITLE")]
		public virtual string FTITLE 
		{ 
		    get
		    {
		        return this._fTITLE;
		    }
		    set
		    {
		        this._fTITLE = value;
		    }
		}
		
		private string _fCONTENT;
		[Column("FCONTENT", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, IsNullable = true, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_fCONTENT")]
		public virtual string FCONTENT 
		{ 
		    get
		    {
		        return this._fCONTENT;
		    }
		    set
		    {
		        this._fCONTENT = value;
		    }
		}
		
		private long? _fTIMESTAMP;
		[Column("FTIMESTAMP", OpenAccessType = OpenAccessType.Int64, IsNullable = true, Length = 0, Scale = 0, SqlType = "bigint")]
		[Storage("_fTIMESTAMP")]
		public virtual long? FTIMESTAMP 
		{ 
		    get
		    {
		        return this._fTIMESTAMP;
		    }
		    set
		    {
		        this._fTIMESTAMP = value;
		    }
		}
		
		private int _fCATEGORY_ID;
		[Column("FCATEGORY_ID", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_fCATEGORY_ID")]
		public virtual int FCATEGORY_ID 
		{ 
		    get
		    {
		        return this._fCATEGORY_ID;
		    }
		    set
		    {
		        this._fCATEGORY_ID = value;
		    }
		}
		
	}
}
